"""cmdb + problem management (fase 6): assets, problems, ticket.asset_id/problem_id

Revision ID: 8a5196020c8d
Revises: a1b2c3d4e5f6
Create Date: 2026-08-19 14:29:50.396631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5196020c8d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('investigating', 'known_error', 'resolved', name='problem_status'), server_default='investigating', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('desktop', 'notebook', 'server', 'printer', 'network', 'other', name='asset_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'maintenance', 'retired', name='asset_status'), server_default='active', nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tickets', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('problem_id', sa.UUID(), nullable=True))
    # Nomeadas explicitamente (autogenerate deixa None, que quebra o downgrade)
    op.create_foreign_key('tickets_asset_id_fkey', 'tickets', 'assets', ['asset_id'], ['id'])
    op.create_foreign_key('tickets_problem_id_fkey', 'tickets', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_problem_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_asset_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'problem_id')
    op.drop_column('tickets', 'asset_id')
    op.drop_table('assets')
    op.drop_table('problems')
    # ### end Alembic commands ###
    # Ajustado à mão: DROP TABLE não derruba os tipos ENUM associados no
    # Postgres — sem isso, um upgrade seguinte falha com "type already
    # exists" ao tentar recriá-los.
    sa.Enum(name='problem_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_type').drop(op.get_bind(), checkfirst=True)
